apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-mongoexpress
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mongoexpress.port }}
      targetPort: {{ .Values.mongoexpress.port }}
      protocol: TCP
      name: {{ .Chart.Name }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
